{% set name = "gooey" %}
{% set version = "1.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Gooey-{{ version }}.tar.gz  # NB: uppercase G in tarball filename
  sha256: 89791a0d0c9d265d96dd48babee8eb0d0d5912b44e984a44c5f7574657dff7aa

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip_compile_pyc:
    - "*/examples/*.py"
  skip: true  # [osx and py<37]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]  
  host:
    - pip
    - python
    - xorg-libxfixes  # [linux]
    - pillow >=4.3.0
    - psutil >=5.4.2
    - colored >=1.3.93
    - pygtrie >=2.3.3
    - wxpython >=4.1.0,<4.2
  run:
    - python
    - pillow >=4.3.0
    - psutil >=5.4.2
    - colored >=1.3.93
    - pygtrie >=2.3.3
    - wxpython >=4.1.0,<4.2

test:
  imports:
    - gooey
    - gooey.gui
    - gooey.gui.components
    - gooey.gui.components.layouts
    - gooey.gui.components.widgets
    - gooey.gui.components.widgets.core
    - gooey.gui.components.widgets.dialogs
    - gooey.gui.containers
    - gooey.gui.lang
    - gooey.gui.util
    - gooey.images
    - gooey.languages
    - gooey.python_bindings
    - gooey.tests
    - gooey.util

about:
  home: http://pypi.python.org/pypi/Gooey
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Turn (almost) any command line program into a full GUI application with one line
  doc_url: https://github.com/chriskiehl/Gooey
  dev_url: https://github.com/chriskiehl/Gooey

extra:
  recipe-maintainers:
    - jfcorbett
    - casperdcl
    - chriskiehl
