{% set name = "gooey" %}
{% set version = "1.0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Gooey-{{ version }}.tar.gz  # NB: uppercase G in tarball filename
  sha256: 08d6bf534f4d50d50dafba5cfc68dcf31a6e9eeef13a94cbe3ea17c4e45c4671

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . -vv
  skip_compile_pyc:
    - '*/examples/*.py'

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - pillow >=4.3.0
    - psutil >=5.4.2
    - colored >=1.3.93
    - pygtrie >=2.3.3
    - wxpython >=4.1.0

test:
  imports:
    - gooey
    - gooey.gui
    - gooey.gui.components
    - gooey.gui.components.layouts
    - gooey.gui.components.widgets
    - gooey.gui.components.widgets.core
    - gooey.gui.components.widgets.dialogs
    - gooey.gui.containers
    - gooey.gui.lang
    - gooey.gui.util
    - gooey.images
    - gooey.languages
    - gooey.python_bindings
    - gooey.tests
    - gooey.util

about:
  home: http://pypi.python.org/pypi/Gooey
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Turn (almost) any command line program into a full GUI application with one line
  doc_url: https://github.com/chriskiehl/Gooey
  dev_url: https://github.com/chriskiehl/Gooey

extra:
  recipe-maintainers:
    - jfcorbett
    - casperdcl
    - chriskiehl
    - ickc
